### PR TITLE
cmake: build gtest if not found

### PR DESCRIPTION
**Pull request by tchaikov**
debian stopped shipping googletest binaries, but it offers googletest in
the source form. so we can use it instead.

Signed-off-by: Kefu Chai <kchai@redhat.com>

### CODE REVIEW

**Comment by ivancich** [comment]
This isn't working for me. I clone git@github.com:google/googletest.git in /home/ivancich/gtest. Then in a "build" subdir from the dmclock tree I execute:

> cmake -DGTEST_ROOT=/home/ivancich/gtest ..

And that output looked fine. But then when I issue:

> VERBOSE=1 make dmclock-sims

And I get as part of the output:

> cd /home/ivancich/dmclock-prs/dmclock/build/sim/src && /usr/lib64/ccache/c++    -I/home/ivancich/dmclock-prs/dmclock/sim/src/ssched -I/home/ivancich/dmclock-prs/dmclock/sim/src/../../src -I/home/ivancich/dmclock-prs/dmclock/sim/src/../../support/src  -std=c++11 -Wno-write-strings -Wall -pthread   -Wall -pthread  -Wno-unused-but-set-variable -Wno-unused-function -o CMakeFiles/dmc_sim.dir/test_dmclock.cc.o -c /home/ivancich/dmclock-prs/dmclock/sim/src/test_dmclock.cc
> In file included from /home/ivancich/dmclock-prs/dmclock/sim/src/test_dmclock.cc:10:0:
> /home/ivancich/dmclock-prs/dmclock/sim/src/../../src/dmclock_server.h:53:30: fatal error: gtest/gtest_prod.h: No such file or directory
>  #include "gtest/gtest_prod.h"
>                               ^
> compilation terminated.

**Comment by tchaikov** [comment]
@ivancich 

fixed and repushed.

you might need to point `GTEST_ROOT` to `/home/ivancich/gtest/googletest`, like
```
$ GTEST_ROOT=/home/ivancich/gtest/googletest cmake . ..
```
or 
```
$ cmake -DGTEST_ROOT=/home/ivancich/gtest/googletest . ..
```

**Comment by ivancich** [comment]
I'm still unable to get it to work. If I do:
`cmake -DGTEST_ROOT=/home/ivancich/gtest/googletest ..`
I get errors that it cannot find the header file as it includes an extra googletest in the path:

> cd /home/ivancich/dmclock-prs/dmclock/build/test && /usr/lib64/ccache/c++    -I/home/ivancich/dmclock-prs/dmclock/build/test -I/home/ivancich/dmclock-prs/dmclock/test/../src -I/home/ivancich/dmclock-prs/dmclock/test/../support/src -I/home/ivancich/dmclock-prs/dmclock/test/../sim/src -I/home/ivancich/gtest/googletest/googletest/include  -std=c++11 -Wno-write-strings -Wall -pthread   -o CMakeFiles/dmclock-tests.dir/test_test_client.cc.o -c /home/ivancich/dmclock-prs/dmclock/test/test_test_client.cc
> /home/ivancich/dmclock-prs/dmclock/test/test_test_client.cc:12:25: fatal error: gtest/gtest.h: No such file or directory
>  #include "gtest/gtest.h"
>                          ^
> compilation terminated.

But if I do:
`cmake -DGTEST_ROOT=/home/ivancich/gtest ..`
It gets past the include issues, but fails later:

> CMakeFiles/Makefile2:313: recipe for target 'test/CMakeFiles/dmclock-tests.dir/all' failed
> make[2]: *** [test/CMakeFiles/dmclock-tests.dir/all] Error 2
> CMakeFiles/Makefile2:325: recipe for target 'test/CMakeFiles/dmclock-tests.dir/rule' failed
> make[1]: *** [test/CMakeFiles/dmclock-tests.dir/rule] Error 2
> Makefile:194: recipe for target 'dmclock-tests' failed
> make: *** [dmclock-tests] Error 2

**Comment by tchaikov** [comment]
@ivancich thanks for your patience and help:

changelog

- only build gtest, as we don't use gmock here. googletest builds gmock and gtest by default.
- add include dir for `dmclock-tests`

it should work now with:
```
cmake -DGTEST_ROOT=/home/ivancich/gtest ..
```

in my case:
```
$ cmake -DGTEST_ROOT=/home/kefu/dev/googletest/ ..
# ...
$ make -j8
# ...
[100%] Built target dmclock-tests
```

**Comment by ivancich** [comment]
Thanks, Kefu! I'll look for the corresponding ceph PR and pull in the latest dmclock code with it.

**Comment by tchaikov** [comment]
@ivancich the ceph PR is https://github.com/ceph/ceph/pull/16286, and i am waiting @myoungwon 's work to generalize the op wq enabling the ordering by op lock. but yeah, i can re-post that PR without https://github.com/ceph/ceph/pull/16286/commits/182280c65e8371730fe842446a0ae5cbd540c1bd. and that PR still makes sense even without the generalization part. but considering the code churn, we will very likely hold the change for mimic.

**Comment by ivancich** [comment]
We can wait; no problem.

**Pull request merged**
